# Generated by Django 6.0.6 on 2026-07-04 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_alter_workspacemembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name displayed on invoices, receipts, and reports.', max_length=255)),
                ('sku', models.CharField(help_text='Stock-keeping unit identifier. Must be unique per workspace.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional product description or notes.')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase cost of the product (before markup).', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price charged to the customer.', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this product is available for sale.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated.')),
                ('workspace', models.ForeignKey(help_text='The workspace this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products_product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['workspace'], name='idx_products_workspace'), models.Index(fields=['sku'], name='idx_products_sku'), models.Index(fields=['is_active'], name='idx_products_is_active')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'sku'), name='uq_products_workspace_sku', violation_error_message='A product with this SKU already exists in this workspace.')],
            },
        ),
    ]
