# Generated by Django 6.0.6 on 2026-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('workspaces', '0004_alter_workspacemembership_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='chk_products_cost_price_non_negative', violation_error_message='Cost price must be greater than or equal to zero.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gt', 0)), name='chk_products_selling_price_positive', violation_error_message='Selling price must be greater than zero.'),
        ),
    ]
