# Generated by Django 6.0.6 on 2026-07-04 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_chk_products_cost_price_non_negative_and_more'),
        ('workspaces', '0004_alter_workspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of line totals before any discounts or taxes.', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Final amount charged to the customer.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the sale was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the sale was last updated.')),
                ('created_by', models.ForeignKey(help_text='The user who created this sale.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace this sale belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units sold. Must be greater than zero.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of sale.', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Computed total for this line item (quantity × unit_price).', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the line item was created.')),
                ('product', models.ForeignKey(help_text='The product sold. Protected to preserve sale history.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(help_text='The sale this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'db_table': 'sales_sale_item',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['workspace'], name='idx_sales_workspace'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_by'], name='idx_sales_created_by'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='idx_sales_created_at'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['workspace', 'created_at'], name='idx_sales_workspace_created'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='chk_sales_subtotal_non_negative', violation_error_message='Subtotal must be greater than or equal to zero.'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_sales_total_non_negative', violation_error_message='Total must be greater than or equal to zero.'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='idx_sale_items_sale'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='idx_sale_items_product'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='idx_sale_items_sale_product'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_sale_items_quantity_positive', violation_error_message='Quantity must be greater than zero.'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_sale_items_unit_price_non_negative', violation_error_message='Unit price must be greater than or equal to zero.'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='chk_sale_items_line_total_non_negative', violation_error_message='Line total must be greater than or equal to zero.'),
        ),
    ]
