# Generated by Django 6.0.6 on 2026-07-06 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('workspaces', '0004_alter_workspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='PENDING_PAYMENT', help_text='Whether the sale has been paid for.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='idx_sales_payment_status'),
        ),
    ]
