# Generated by Django 6.0.6 on 2026-07-04 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_alter_workspacemembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the customer.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Customer's given name.", max_length=150)),
                ('last_name', models.CharField(blank=True, help_text="Customer's family name (optional).", max_length=150)),
                ('phone_number', models.CharField(help_text='Primary contact phone number. Must be unique per workspace.', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Optional email address.', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Optional street address or location details.')),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes about the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the customer was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the customer was last updated.')),
                ('workspace', models.ForeignKey(help_text='The workspace this customer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace'], name='idx_customers_workspace'), models.Index(fields=['phone_number'], name='idx_customers_phone'), models.Index(fields=['email'], name='idx_customers_email')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'phone_number'), name='uq_customers_workspace_phone', violation_error_message='A customer with this phone number already exists in this workspace.')],
            },
        ),
    ]
