# Generated by Django 6.0.6 on 2026-07-01 13:36

import django.contrib.auth.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, help_text='Primary login identifier. Must be unique.', max_length=254, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('first_name', models.CharField(blank=True, help_text='Given name.', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Family name.', max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number (E.164 format recommended).', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log into the platform. Unselect this instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.')),
                ('is_merchant', models.BooleanField(default=True, help_text='Indicates whether the user registered as a business owner. Super-admins have this set to False.')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email address has been verified.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user was last updated.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'indexes': [models.Index(fields=['email'], name='idx_accounts_user_email'), models.Index(fields=['username'], name='idx_accounts_user_username')],
            },
        ),
    ]
