# Generated by Django 6.0.6 on 2026-07-04 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        ('workspaces', '0004_alter_workspacemembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the payment.', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount. Must be a positive value.', max_digits=12)),
                ('currency', models.CharField(default='NGN', help_text='ISO-4217 currency code (e.g. NGN, USD).', max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('CARD', 'Card Payment'), ('POS', 'POS Terminal'), ('OTHER', 'Other')], help_text='How the payment was made.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current payment status.', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text='External reference from the payment provider (e.g. Nomba transaction ID).', max_length=255, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Internal reference for the payment (e.g. receipt number).', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the payment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment was last updated.')),
                ('customer', models.ForeignKey(blank=True, help_text='Optional customer who made the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer')),
                ('sale', models.ForeignKey(help_text='The sale this payment is for. Protected to preserve payment history.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
                ('workspace', models.ForeignKey(help_text='The workspace this payment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace'], name='idx_payments_workspace'), models.Index(fields=['sale'], name='idx_payments_sale'), models.Index(fields=['status'], name='idx_payments_status'), models.Index(fields=['provider_reference'], name='idx_payments_provider_ref'), models.Index(fields=['workspace', 'created_at'], name='idx_payments_ws_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payments_amount_positive', violation_error_message='Payment amount must be greater than zero.')],
            },
        ),
    ]
