# Generated by Django 6.0.6 on 2026-07-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
        ('workspaces', '0004_alter_workspacemembership_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('sale',), name='uq_payments_single_success_per_sale', violation_error_message='A successful payment already exists for this sale.'),
        ),
    ]
