# Generated by Django 6.0.6 on 2026-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_webhook_event_and_provider_ref_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='uq_payments_provider_reference',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, help_text='External reference from the payment provider (e.g. Nomba transaction ID). Uniqueness is enforced via a conditional unique index (only non-NULL values).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(help_text='Unique event identifier from the provider. Used for idempotency — the same event_id is never processed twice.', max_length=255, unique=True),
        ),
    ]
