# Generated by Django 6.0.6 on 2026-07-01 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text="Machine-readable action identifier, e.g. 'entity.create.product'.", max_length=50)),
                ('target_type', models.CharField(blank=True, help_text="Type of the affected entity, e.g. 'product', 'sale'.", max_length=50, null=True)),
                ('target_id', models.UUIDField(blank=True, help_text='UUID of the affected entity.', null=True)),
                ('changes', models.JSONField(blank=True, help_text="JSON object with 'before' and 'after' snapshots.", null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata (ip_address, user_agent, correlation_id).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace context (null for system-wide actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'common_auditlog',
                'indexes': [models.Index(fields=['workspace'], name='idx_auditlog_workspace'), models.Index(fields=['actor'], name='idx_auditlog_actor'), models.Index(fields=['target_type', 'target_id'], name='idx_auditlog_target'), models.Index(fields=['action'], name='idx_auditlog_action'), models.Index(fields=['created_at'], name='idx_auditlog_created')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('low_stock_alert', 'Low Stock Alert'), ('sale_completed', 'Sale Completed'), ('staff_invite', 'Staff Invite'), ('payment_received', 'Payment Received')], help_text='Category of the notification event.', max_length=30)),
                ('title', models.CharField(help_text='Short notification title.', max_length=255)),
                ('message', models.TextField(help_text='Full notification body.')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification.')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user read the notification.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-delete after this timestamp.', null=True)),
                ('user', models.ForeignKey(help_text='Recipient of the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Optional workspace context for the notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'common_notification',
                'indexes': [models.Index(fields=['user'], name='idx_notifications_user'), models.Index(fields=['user', 'is_read'], name='idx_notifications_user_unread'), models.Index(fields=['expires_at'], name='idx_notifications_expires')],
            },
        ),
    ]
