# Generated by Django 6.0.6 on 2026-07-04 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_chk_products_cost_price_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity. Cannot be negative.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the inventory record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the inventory record was last updated.')),
                ('product', models.OneToOneField(help_text='The product this inventory record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory_inventory',
                'indexes': [models.Index(fields=['product'], name='idx_inventory_product')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_inventory_quantity_non_negative', violation_error_message='Quantity cannot be negative.')],
            },
        ),
    ]
