# Generated by Django 6.0.6 on 2026-07-01 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business name displayed across the platform.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the workspace.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this workspace is active and accessible.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the workspace was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the workspace was last updated.')),
                ('owner', models.ForeignKey(help_text='User who created and owns this workspace.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspaces_workspace',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner'], name='idx_workspaces_owner'), models.Index(fields=['slug'], name='idx_workspaces_slug'), models.Index(fields=['is_active'], name='idx_workspaces_is_active')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='uq_workspaces_owner_name', violation_error_message='You already have a workspace with this name.')],
            },
        ),
    ]
