# Generated by Django 6.0.6 on 2026-07-01 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(blank=True, help_text='Registered business name (if different from workspace name).', max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='Tax registration number (VAT, EIN, etc.).', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Business contact phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Business contact email address.', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Business physical address.')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code for the workspace.', max_length=3)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone identifier for the workspace.', max_length=64)),
                ('logo', models.ImageField(blank=True, help_text='Business logo image.', null=True, upload_to='business_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the profile was last updated.')),
                ('workspace', models.OneToOneField(help_text='The workspace this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'db_table': 'workspaces_business_profile',
            },
        ),
    ]
