# Generated by Django 6.0.6 on 2026-07-02 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_businessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], help_text='Role assigned to the user within this workspace.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this membership is active and the user can access the workspace.')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user joined the workspace.')),
                ('user', models.ForeignKey(help_text='The user who is a member of the workspace.', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace the user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Membership',
                'verbose_name_plural': 'Workspace Memberships',
                'db_table': 'workspaces_workspace_membership',
                'indexes': [models.Index(fields=['workspace', 'role'], name='idx_ws_membership_ws_role')],
                'constraints': [models.UniqueConstraint(fields=('user', 'workspace'), name='uq_ws_membership_user_workspace', violation_error_message='This user is already a member of this workspace.')],
            },
        ),
    ]
