# Generated by Django 6.0.6 on 2026-07-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspacemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], help_text='Role assigned to the user within this workspace.', max_length=10),
        ),
    ]
