"""
Checkout service for the Nomba API.

Provides :class:`NombaCheckoutService` which creates online checkout
orders, and :class:`CheckoutOrderResult` which encapsulates the
response returned by Nomba after a successful order creation.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from typing import Any

from apps.payments.integrations.nomba.client import NombaClient
from apps.payments.integrations.nomba.exceptions import (
    NombaInvalidResponseError,
)


@dataclass(frozen=True)
class CheckoutOrderResult:
    """A successful Nomba checkout order creation response.

    Parameters
    ----------
    checkout_link:
        The URL to redirect the customer to for payment completion.
    order_reference:
        The unique reference for this order (either the one provided
        by the merchant or generated by Nomba).
    raw_response:
        The complete Nomba API response body, preserved for debugging
        and auditing purposes.  **Do not** depend on its structure in
        production code.
    """

    checkout_link: str
    order_reference: str
    raw_response: dict[str, Any]


class NombaCheckoutService:
    """Create online checkout orders on Nomba.

    This service is **auth-agnostic** — it expects a valid bearer
    token and account identifier to be supplied by the caller (e.g.
    from :class:`apps.payments.integrations.nomba.auth.NombaAuthService`).

    Usage::

        auth = NombaAuthService()
        token = auth.get_access_token()

        checkout = NombaCheckoutService(
            access_token=token.access_token,
            account_id=settings.NOMBA_ACCOUNT_ID,
        )
        result = checkout.create_order(amount="10000.00")
        print(result.checkout_link)
    """

    # Default timeout: 10 s connect, 30 s read.
    _REQUEST_TIMEOUT: tuple[float, float] = (10.0, 30.0)

    def __init__(
        self,
        access_token: str,
        account_id: str,
        base_url: str = "",
    ) -> None:
        """Initialise the checkout service.

        Parameters
        ----------
        access_token:
            A valid Nomba OAuth2 bearer token.
        account_id:
            The Nomba account identifier to attach to API requests
            via the ``accountId`` header.
        base_url:
            The Nomba API base URL.  If empty, it must be set via
            ``settings.NOMBA_BASE_URL`` at call time; normally you
            pass it explicitly from the environment that obtained
            the token.
        """
        self._access_token = access_token
        self._account_id = account_id
        self._base_url = base_url

        self._validate_config()

        from django.conf import settings as django_settings

        if not self._base_url:
            self._base_url = django_settings.NOMBA_BASE_URL

        self._client = NombaClient(
            base_url=self._base_url,
            timeout=self._REQUEST_TIMEOUT,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def create_order(
        self,
        amount: str,
        currency: str = "NGN",
        callback_url: str | None = None,
        customer_email: str | None = None,
        order_reference: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> CheckoutOrderResult:
        """Create a checkout order on Nomba.

        .. warning::

            **This method MUST never set a Payment to ``SUCCESS``.**
            It only creates an order on Nomba and returns the
            checkout link. The ``Payment`` is created as ``PENDING``
            by :class:`NombaPaymentService`.

            Only :class:`apps.payments.services.PaymentService`
            may update payment status. Both the manual ``/verify/``
            endpoint and the ``/webhooks/nomba/`` endpoint delegate
            to ``PaymentService.update_payment_status()``.

        Sends a ``POST`` request to ``/v1/checkout/order`` with the
        order details.

        If ``order_reference`` is not provided, a UUID v4 string is
        generated automatically.

        Parameters
        ----------
        amount:
            The order amount as a string (e.g. ``"10000.00"``).
        currency:
            ISO 4217 currency code (e.g. ``"NGN"``).  Defaults to
            ``"NGN"``.
        callback_url:
            Optional HTTPS URL to redirect the customer to after
            payment.
        customer_email:
            Optional customer email address for receipt delivery.
        order_reference:
            Optional unique identifier for this order.  A UUID v4 is
            generated if omitted.
        metadata:
            Optional arbitrary key-value metadata attached to the
            order.

        Returns
        -------
        CheckoutOrderResult
            A frozen dataclass containing **only** the checkout link
            and order reference. **Never** contains a payment status
            or attempts to set ``SUCCESS``.

        Raises
        ------
        NombaAuthenticationError
            If the access token is invalid or expired (HTTP 401/403).
        NombaConnectionError
            If a network error or timeout occurs.
        NombaInvalidResponseError
            If Nomba returns a malformed (non-JSON) response, or the
            response structure does not match the documented schema.
        NombaRequestError
            If Nomba returns an unexpected non-2xx response.
        """
        if not amount:
            raise ValueError(
                "amount must be a non-empty string, e.g. '10000.00'"
            )

        resolved_reference = order_reference or str(uuid.uuid4())

        payload: dict[str, Any] = {
            "order": {
                "amount": amount,
                "currency": currency,
                "orderReference": resolved_reference,
            },
            "tokenizeCard": False,
        }

        if callback_url is not None:
            payload["order"]["callbackUrl"] = callback_url

        if customer_email is not None:
            payload["order"]["customerEmail"] = customer_email

        if metadata is not None:
            payload["meta"] = metadata

        headers = {
            "Authorization": f"Bearer {self._access_token}",
            "accountId": self._account_id,
        }

        response = self._client.post(
            "/v1/checkout/order",
            json=payload,
            headers=headers,
        )

        body: dict[str, Any] = NombaClient.parse_json(response)
        data: dict[str, Any] = self._validate_response(body)

        checkout_link = str(data["checkoutLink"])
        order_reference = str(
            data.get("orderReference", resolved_reference)
        )

        return CheckoutOrderResult(
            checkout_link=checkout_link,
            order_reference=order_reference,
            raw_response=body,
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _validate_config(self) -> None:
        """Verify that required constructor args are non-empty.

        Raises
        ------
        ValueError
            If ``access_token`` or ``account_id`` is empty.
        """
        if not self._access_token:
            raise ValueError(
                "access_token is required and must be non-empty. "
                "Obtain a token from NombaAuthService.get_access_token()."
            )
        if not self._account_id:
            raise ValueError(
                "account_id is required and must be non-empty. "
                "Set NOMBA_ACCOUNT_ID in your Django settings."
            )

    @staticmethod
    def _validate_response(body: Any) -> dict[str, Any]:
        """Validate the Nomba checkout response envelope.

        The Nomba checkout endpoint returns::

            {
                "code": "00",
                "description": "checkout order created successful",
                "status": false,
                "data": {
                    "success": true,
                    "message": "success",
                    "checkoutLink": "...",
                    "orderReference": "..."
                }
            }

        Success is determined by:
        - ``code == "00"`` (same as the auth endpoint)
        - ``data.success == True``
        - ``data.checkoutLink`` is present and non-empty

        Parameters
        ----------
        body:
            The parsed JSON response body.

        Returns
        -------
        dict[str, Any]
            The validated ``data`` sub-dict.

        Raises
        ------
        NombaInvalidResponseError
            If the response is missing required fields or indicates
            failure.
        """
        if not isinstance(body, dict):
            raise NombaInvalidResponseError(
                f"Nomba checkout response body is not a JSON object: "
                f"{body!r}"
            )

        # Nomba returns code="00" for a successful API call
        code: Any = body.get("code")
        if code != "00":
            raise NombaInvalidResponseError(
                f"Nomba checkout failed (code={code!r}). "
                f"Expected '00'."
            )

        data: Any = body.get("data")

        if not isinstance(data, dict):
            raise NombaInvalidResponseError(
                "Nomba checkout response is missing the 'data' envelope"
            )

        # Check that Nomba reports success within the data envelope
        if not data.get("success"):
            raise NombaInvalidResponseError(
                f"Nomba checkout data indicates failure (success=false, "
                f"message={data.get('message', 'N/A')!r})"
            )

        checkout_link: Any = data.get("checkoutLink")

        if not checkout_link:
            raise NombaInvalidResponseError(
                "Nomba checkout response is missing 'checkoutLink' in data"
            )

        return data
