# Generated by Django 6.0.6 on 2026-07-04 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment')], help_text='The type of stock movement: sale, restock, or adjustment.', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units moved.')),
                ('quantity_before', models.PositiveIntegerField(help_text='Stock quantity before the movement.')),
                ('quantity_after', models.PositiveIntegerField(help_text='Stock quantity after the movement.')),
                ('reference', models.CharField(blank=True, default='', help_text='Optional human-readable reference (e.g. "Sale #123", "PO-001").', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the movement was recorded.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who caused the movement. May be null for automated processes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(help_text='The inventory record that was changed.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements_stockmovement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory'], name='idx_stock_movements_inventory'), models.Index(fields=['movement_type'], name='idx_stock_movements_type'), models.Index(fields=['created_at'], name='idx_stock_movements_created'), models.Index(fields=['inventory', 'created_at'], name='idx_stock_movements_inv_cr')],
            },
        ),
    ]
